### ISSUE TITLE
Resolver trying to resolve everything?

### ISSUE THREAD

**Issue by junqdu** [mjeanroy/bower-npm-resolver#248]
I have one dependency that is trying to use the npm resolve, but when I perform 
`bower install --verbose --force`

It seems like it is trying to resolve everything, e.g., angular: 
```
bower install --verbose --force
bower angular-animate#=1.6.9     npm-resolver initializing bower-npm-resolver 0.10.0
bower angular-animate#=1.6.9     npm-resolver found matchers: [{"regexp":{},"replace":""},{"regexp":{},"replace":""}]
bower angular#1.6.9              npm-resolver initializing bower-npm-resolver 0.10.0
bower angular#1.6.9              npm-resolver found matchers: [{"regexp":{},"replace":""},{"regexp":{},"replace":""}]
bower angular-material#=1.1.13   npm-resolver initializing bower-npm-resolver 0.10.0
bower angular-material#=1.1.13   npm-resolver found matchers: [{"regexp":{},"replace":""},{"regexp":{},"r

...


bower angular-animate#=1.6.9                                    npm-resolver checking for: angular-animate
bower angular#1.6.9                                             npm-resolver checking for: angular
bower angular-material#=1.1.13                                  npm-resolver checking for: angular-material
bower angular-aria#1.4 - 1.7.0 || ^1.7.2                        npm-resolver checking for: angular-aria
bower angular-messages#1.4 - 1.7.0 || ^1.7.2                    npm-resolver checking for: angular-messages

```

**Comment by mjeanroy** [comment]
@junqdu Sorry for the (very long) delay. Can you share what's in your `.bowerrc` file please?

**Comment by junqdu** [comment]
@mjeanroy Thanks for getting back to me

```
{
  "directory": "bower_components",
  "resolvers": [
    "bower-npm-resolver"
  ]
}
```

**Comment by mjeanroy** [comment]
@junqdu The messages you saw are related to bower instantiating the resolver for each dependencies. 

This is the expected behavior, since for each dependency, bower will execute the `match` function of `bower-npm-resolver` to know if it should use this custom resolver or not.

If `bower-npm-resolver` is really used to fetch your dependency, you should see a log like:

`bower [you depedency]        npm-resolver downloading tarball for: [you dependency].`

As long as you don't see this log (using `--verbose`), then bower use the default resolvers.
